sudo: required

services:
  - docker

git:
  depth: 1

before_install:
- docker pull centos:7.4.1708

script:
- docker build -t rainbond/pkg-download:centos-7.4-v5.1 download/centos-7
- docker run --rm -v ${PWD}/rpm/centos/7:/opt/rainbond/install/install/pkgs/centos rainbond/pkg-download:centos-7.4-v5.1
- sudo chmod -R 755 ${PWD}/rpm
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push rainbond/pkg-download:centos-7.4-v5.1




