sudo: required

services:
  - docker

git:
  depth: 1

before_install:
- docker pull centos:7.4.1708
- docker pull centos:7.6.1810

script:
- docker build -t rainbond/pkg-download:centos-7.4-v5.x download/centos-7.4
- docker build -t rainbond/pkg-download:centos-7.6-v5.x download/centos-7.6
- docker run --rm -v ${PWD}/rpm/centos/7.4:/opt/rainbond/install/install/pkgs/centos rainbond/pkg-download:centos-7.4-v5.x
- docker run --rm -v ${PWD}/rpm/centos/7.6:/opt/rainbond/install/install/pkgs/centos rainbond/pkg-download:centos-7.6-v5.x
- docker build -t rainbond/pkg-repo:centos-7.x-v5.x .
- sudo chmod -R 755 ${PWD}/rpm
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push rainbond/pkg-download:centos-7.4-v5.x
- docker push rainbond/pkg-download:centos-7.6-v5.x
- docker push rainbond/pkg-repo:centos-7.x-v5.x




